/**
 * What it takes to point the template at a subscription, and nothing more.
 *
 * **The deliberate line here is that this generates a *preview* and not a deployment.** `what-if` is
 * read-only: it asks Azure what applying the template would change and prints the answer. That is the
 * whole of what a graph viewer should be able to set off on its own, because the alternative is a
 * right-click in a diagram mutating a subscription — and which subscription depends on whoever was
 * logged in.
 *
 * So a `what-if.ps1` is generated and a `deploy.ps1` is not. The command that actually deploys is in
 * the README instead, as text a person has to read and paste. That is not an accident of effort: a
 * script in the folder is a thing somebody double-clicks, and the folder is full of files whose header
 * says a generator owns them.
 */

export interface DeployFiles {
  readonly path: string;
  readonly content: string;
}

/** The parameter file: what the model does not know, with nowhere to hide. */
export function parameters(template: string, namespaceParam: string): DeployFiles {
  return {
    path: template.replace(/\.bicep$/, ".bicepparam"),
    content: `${[
      "// <auto-generated>",
      "//   Generated from a 7K model, and the one file here you are meant to edit: it holds what the",
      "//   model does not know. Replaced on the next run, so keep the real values somewhere else —",
      "//   a key vault reference, or your pipeline's variables.",
      "// </auto-generated>",
      "",
      `using '${template.split("/").pop()}'`,
      "",
      "// The namespace these entities belong to. A namespace outlives any one model, which is why it",
      "// is a parameter and not a resource.",
      `param ${namespaceParam} = '<your-service-bus-namespace>'`,
      "",
    ].join("\n")}`,
  };
}

/**
 * A read-only preview, for every template beside it.
 *
 * Discovers the templates rather than being told, so that one script serves `single`, `per-package`
 * and `per-declaration` without the generator having to know which.
 */
export function whatIf(): DeployFiles {
  return {
    path: "what-if.ps1",
    content: `${[
      "# <auto-generated>",
      "#   Generated from a 7K model. Replaced wholesale on the next run.",
      "#",
      "#   This asks Azure what deploying would change, and changes nothing. It is the only thing in",
      "#   this folder that is safe to run without reading first, which is why it is the only script",
      "#   here — the command that actually deploys is in the README, as text a person has to paste.",
      "# </auto-generated>",
      "",
      "[CmdletBinding()]",
      "param(",
      "    [Parameter(Mandatory = $true)][string] $ResourceGroup,",
      "    [string] $Subscription",
      ")",
      "",
      "$ErrorActionPreference = 'Stop'",
      "",
      "if ($Subscription) { az account set --subscription $Subscription }",
      "",
      "$templates = Get-ChildItem -Path $PSScriptRoot -Filter *.bicep -Recurse | Sort-Object FullName",
      "if (-not $templates) { throw 'No templates beside this script.' }",
      "",
      "foreach ($template in $templates) {",
      "    $params = [System.IO.Path]::ChangeExtension($template.FullName, '.bicepparam')",
      "    Write-Host \"\" ",
      "    Write-Host \"what-if: $($template.Name)\" -ForegroundColor Cyan",
      "",
      "    # `what-if` is read-only. It reports what a deployment would add, change and delete, and",
      "    # the deletions are the ones to read twice: a pipe removed from the model is an entity",
      "    # removed from Azure, and whatever was still in it goes with it.",
      "    $arguments = @('deployment', 'group', 'what-if',",
      "                   '--resource-group', $ResourceGroup,",
      "                   '--template-file', $template.FullName)",
      "    if (Test-Path $params) { $arguments += @('--parameters', $params) }",
      "",
      "    az @arguments",
      "    if ($LASTEXITCODE -ne 0) { throw \"what-if failed for $($template.Name)\" }",
      "}",
      "",
    ].join("\n")}`,
  };
}

/** What a reader needs before running any of it. */
export function readme(templates: readonly string[], namespaceParam: string, sku: string): DeployFiles {
  const first = templates[0] ?? "main.bicep";
  return {
    path: "README.md",
    content: `${[
      "<!-- Generated from a 7K model. Replaced wholesale on the next run. -->",
      "",
      "# Topology",
      "",
      "Azure Service Bus entities for the pipes a 7K model declares. One pipe is one queue or topic,",
      "and a service's `reacts` clause is a subscription with the filter the model implies.",
      "",
      "## This is a shape, not a deployment",
      "",
      "These templates say what the topology should be. They do not know what is deployed, so they",
      "cannot tell you what applying them would do — only Azure can:",
      "",
      "```powershell",
      "./what-if.ps1 -ResourceGroup <group>",
      "```",
      "",
      "That is read-only. **Read the deletions.** A pipe removed from the model is an entity removed",
      "from Azure, and whatever was still queued in it goes too.",
      "",
      "When the preview says what you expect:",
      "",
      "```powershell",
      `az deployment group create --resource-group <group> --template-file ${first} \\`,
      `  --parameters ${first.replace(/\.bicep$/, ".bicepparam")}`,
      "```",
      "",
      "There is no `deploy.ps1` on purpose. A script in a folder is a thing somebody double-clicks,",
      "and every other file here is owned by a generator.",
      "",
      "## What you have to supply",
      "",
      `Edit the \`.bicepparam\` beside each template. \`${namespaceParam}\` is the only required one: a`,
      "namespace outlives any one model, so it is referenced rather than declared.",
      "",
      `Generated for a **${sku}** namespace. The SKU is not only a parameter — it decides what is`,
      "expressible, so changing it means generating again rather than editing the template.",
      "",
      "## Two conventions the model depends on",
      "",
      "A generated subscription filter reads two things off the message, and a sender that does not set",
      "them will have its messages filtered away:",
      "",
      "- **`sys.Label`** must be the message's qualified 7K name — `shop.orders.PlaceOrder`.",
      "- **An envelope field** travels as a message property of the same name, so a `where` over",
      "  `envelope.priority` reads a property called `priority`.",
      "",
      "Where a pipe declares `ordering by`, its entities require **sessions**: the sender sets",
      "`SessionId` to that field and the receiver has to be session-aware. That changes the handler,",
      "not just the template.",
      "",
      "## What is not here",
      "",
      "- **Authorisation.** A `requires claim …` is a claim check, and Service Bus authorises by role.",
      "- **A `stream`.** That is an Event Hub: a different resource, with partitions and replay.",
      "- **`at-most-once`.** It is a receiver mode, not a property of an entity.",
      "",
      "Each generated file lists what the model declared that it could not carry.",
      "",
    ].join("\n")}`,
  };
}
