/**
 * A Bicep provider for 7K.
 *
 * Its own repository, because D48 puts implementations outside the language: 7K states what the
 * topology must be and this says whether Azure Service Bus can be it.
 *
 * **Only the Topology layer is here, which is the mirror of the SQL provider.** A pipe is a queue; a
 * topic's subscribers are subscriptions; `where` is a subscription filter. A *message* is not
 * infrastructure — a template cannot hold a `decimal(18,2)` — so the Data layer is somebody else's job,
 * and a service is not infrastructure either: it is code, and what it runs on the model does not say.
 *
 * **What the model states is a literal; what it does not is a parameter.** The namespace, the location
 * and the SKU are deployment facts, so they are `param`s. Every property that comes from the model is
 * written out, so that `--check` sees drift when the model changes and a reviewer sees in the diff
 * exactly which declaration moved.
 *
 * **It generates the topology, not the deployment.** The template is what the model implies; applying
 * it to a subscription is a deliberate act, and `az deployment group what-if` is the way to see what
 * would change first. The generated `README` says so, because a template that looks ready to run is
 * how somebody deploys to the wrong place.
 */

import type { Decl, LinkedModel, PipeIr, ReactIr, ServiceIr } from "@sevenk/core";
import type { Artifact, Generated, Loss, OptionSpec, Provider, Refusal, Request } from "@sevenk/generate";
import {
  deadLetterOf,
  forTarget,
  propertiesFor,
  type Property,
  type Sku,
  type Target,
} from "./azure.js";
import { LABEL, typeFilter, whereFilter } from "./filters.js";
import { parameters, readme, whatIf } from "./deploy.js";
import { checkName, qnameOf, qualified, symbol, type NameProblem } from "./naming.js";

const OPTIONS: readonly OptionSpec[] = [
  {
    name: "apiVersion",
    describe:
      "The Service Bus resource API version. Pinned rather than floating: a template that silently changes meaning when Azure ships a new version is a template nobody can review.",
    type: "string",
    default: "2022-10-01-preview",
    scope: "entry",
  },
  {
    name: "sku",
    describe:
      "What the namespace is bought as. Not only a parameter: the SKU decides what is *expressible*, so the generator has to know it. Premium can cap message size and has no express entities; standard is the other way round.",
    type: "enum",
    of: ["standard", "premium"],
    default: "standard",
    scope: "entry",
  },
  {
    name: "namespaceParam",
    describe:
      "The parameter naming the Service Bus namespace to deploy into. An existing namespace by default, because a namespace outlives any one model.",
    type: "string",
    default: "serviceBusNamespace",
    scope: "entry",
  },
  {
    name: "createNamespace",
    describe:
      "Declare the namespace as well as its entities. Off by default: a namespace is usually older than the model and shared with things the model does not know about.",
    type: "boolean",
    default: false,
    scope: "entry",
  },
  {
    name: "deployFiles",
    describe:
      "Emit a `.bicepparam` beside each template, a read-only `what-if.ps1`, and a README. The preview is what a host like Spider can safely offer on a right-click; there is deliberately no deploy script, because a script in a folder is a thing somebody double-clicks.",
    type: "boolean",
    default: true,
    scope: "entry",
  },
  {
    name: "subscriptions",
    describe:
      "Declare a subscription per consumer of a topic, with the filter the model implies. Turning it off leaves the topics and lets a team manage subscribers elsewhere.",
    type: "boolean",
    default: true,
    scope: "declaration",
  },
  {
    name: "typeFilters",
    describe:
      "Filter a subscription to the message types it reacts to. Needs the sender to set `sys.Label` to the message's qualified 7K name; without that convention a filter would drop everything.",
    type: "boolean",
    default: true,
    scope: "declaration",
  },
];

const HEADER = [
  "// <auto-generated>",
  "//   Generated from a 7K model. Do not edit: this file is owned by the generator and is replaced",
  "//   wholesale on the next run. Write what the model does not describe beside it, not inside it.",
  "//",
  "//   This is the topology the model implies, not a deployment. `az deployment group what-if` shows",
  "//   what applying it would change, and is the thing to run first.",
  "// </auto-generated>",
];

const indent = (lines: readonly string[]): string[] => lines.map((l) => (l === "" ? "" : `  ${l}`));

function wrap(text: string, width = 104): string[] {
  const out: string[] = [];
  let line = "";
  for (const word of text.split(/\s+/).filter((w) => w !== "")) {
    if (line !== "" && `${line} ${word}`.length > width) {
      out.push(line);
      line = word;
    } else {
      line = line === "" ? word : `${line} ${word}`;
    }
  }
  if (line !== "") out.push(line);
  return out;
}

const comment = (text: string): string[] => wrap(text).map((l) => `// ${l}`);

/**
 * What a retry policy is, in a broker: the attempts before a message is dead-lettered.
 *
 * The most forgiving of the clauses that share the entity, because one `maxDeliveryCount` serves all
 * of them and a smaller one would dead-letter a message another clause would still have retried.
 */
function deliveryCount(reacts: readonly ReactIr[]): Omit<Property, "on"> | undefined {
  const retries = reacts.map((r) => r.retry?.retries).filter((n): n is number => n !== undefined);
  if (retries.length === 0) return undefined;
  const most = Math.max(...retries);
  return {
    key: "maxDeliveryCount",
    value: String(most + 1),
    why:
      retries.length === 1
        ? `\`retry ${most}\`, plus the first attempt`
        : `the most forgiving \`retry\` of the clauses sharing this entity (${most}), plus the first attempt`,
  };
}

/** One subscription of a topic: a service's consumption of it, under the name the model gives. */
interface Subscriber {
  readonly name: string;
  readonly service: ServiceIr;
  readonly reacts: readonly ReactIr[];
  readonly types: readonly string[];
}

/**
 * Who subscribes to a pipe, grouped the way the model groups them.
 *
 * By `(service, subscription name)` and not by message: `TicketService` reacting to both `ReserveSeats`
 * and `ReleaseSeats` from one pipe has **one** subscription receiving both, which is what 7K's
 * subscription name already says. A second `reacts … as reconcile` is a second subscription, because
 * the model gave it its own name.
 */
function subscribersOf(pipe: PipeIr, model: LinkedModel): Subscriber[] {
  const byName = new Map<string, { service: ServiceIr; reacts: ReactIr[] }>();

  for (const decl of model.decls) {
    if (decl.kind !== "service" || decl.external) continue;
    for (const react of decl.reacts) {
      const target = model.declFor(react.pipe);
      if (target === undefined || qnameOf(target) !== qnameOf(pipe)) continue;
      const held = byName.get(react.subscription);
      if (held === undefined) byName.set(react.subscription, { service: decl, reacts: [react] });
      else held.reacts.push(react);
    }
  }

  return [...byName].map(([name, { service, reacts }]) => ({
    name,
    service,
    reacts,
    types: [
      ...new Set(
        reacts
          .map((r) => model.declFor(r.message))
          .filter((d): d is Decl => d !== undefined)
          .map(qnameOf),
      ),
    ],
  }));
}

/** `properties: { … }` with a comment above each, so a reader can see which declaration asked. */
function propertyBlock(properties: readonly Property[]): string[] {
  if (properties.length === 0) return ["properties: {}"];
  return [
    "properties: {",
    ...indent(
      properties.flatMap((property) =>
        property.key === "$comment"
          ? comment(property.why)
          : [...comment(property.why), `${property.key}: ${property.value}`],
      ),
    ),
    "}",
  ];
}

interface Built {
  readonly lines: readonly string[];
  readonly losses: readonly Loss[];
  readonly problems: readonly NameProblem[];
  readonly needsPremium: boolean;
}

interface Options {
  readonly apiVersion: string;
  readonly sku: Sku;
  readonly namespaceParam: string;
  readonly subscriptions: boolean;
  readonly typeFilters: boolean;
}

/** One pipe, as the resources it needs. */
function pipeResources(pipe: PipeIr, model: LinkedModel, options: Options): Built {
  const name = qnameOf(pipe);
  const lines: string[] = [];
  const losses: Loss[] = [];
  const problems: NameProblem[] = [];

  // A stream is an Event Hub, which is a different resource with a different vocabulary. Saying so is
  // better than deploying a queue and letting somebody find out that nothing replays.
  if (pipe.pipeKind === "stream") {
    losses.push({
      construct: "stream",
      at: name,
      fidelity: "none",
      detail:
        "A `stream` is an Event Hub rather than a Service Bus entity — a different resource, with " +
        "partitions and a consumer group instead of a subscription, and replay instead of a queue. " +
        "This provider does not generate one, so nothing is deployed for this pipe.",
    });
    return { lines: [], losses, problems, needsPremium: false };
  }

  const kind = pipe.pipeKind;
  const nameProblem = checkName(name, kind, name);
  if (nameProblem !== undefined) problems.push(nameProblem);

  const mapped = propertiesFor(pipe, name, options.sku);
  losses.push(...mapped.losses);

  const dead = deadLetterOf(pipe, (ref) => {
    const target = model.declFor(ref);
    return target === undefined ? undefined : qnameOf(target);
  });

  const properties: Property[] = [...mapped.properties];

  // Dead-lettering is a queue's own and a *subscription's* on a topic: a topic has no dead letters,
  // because it holds nothing. Putting it on the topic is a template that will not compile, which is
  // the kind of thing only the schema knows.
  const deadOn: Target[] = kind === "queue" ? ["queue"] : ["subscription"];
  const forTopic = kind === "topic" ? " Its subscriptions carry it, because a topic holds nothing" : "";

  if (dead.k === "none") {
    properties.push({
      key: "deadLetteringOnMessageExpiration",
      value: "false",
      why: `\`dlq none\`: a message this pipe cannot deliver is discarded, and nothing holds it.${forTopic}`,
      on: deadOn,
    });
  } else if (dead.k === "forward") {
    properties.push({
      key: "forwardDeadLetteredMessagesTo",
      value: `'${dead.to}'`,
      why:
        `\`dlq ${dead.to}\`, which is a pipe of its own rather than the built-in dead-letter ` +
        `queue.${forTopic}`,
      on: deadOn,
    });
  } else {
    properties.push({
      key: "deadLetteringOnMessageExpiration",
      value: "true",
      why:
        `the implicit \`${name}.dead\` is Service Bus's own dead-letter sub-queue — it exists already, ` +
        `so nothing is declared for it.${forTopic}`,
      on: deadOn,
    });
  }

  // A queue's consumers share the entity, so its delivery count comes from whatever they declare.
  if (kind === "queue") {
    const count = deliveryCount(subscribersOf(pipe, model).flatMap((s) => s.reacts));
    if (count !== undefined) properties.push({ ...count, on: ["queue"] });
  }

  const resource = symbol(`${kind}_${name}`);
  const parentRef = symbol("namespace");

  lines.push(
    ...comment(`\`${name}\`: a ${pipe.pipeKind} the model declares.`),
    `resource ${resource} 'Microsoft.ServiceBus/namespaces/${kind}s@${options.apiVersion}' = {`,
    ...indent([
      `parent: ${parentRef}`,
      `name: '${name}'`,
      ...propertyBlock(forTarget(properties, kind)),
    ]),
    "}",
    "",
  );

  // A queue has consumers but no subscriptions: receivers share the one entity.
  if (kind === "topic" && options.subscriptions) {
    const subscribers = subscribersOf(pipe, model);

    // Everything a topic declares that only a subscription can carry has nowhere to go when nothing
    // subscribes — and `dlq none` quietly not applying is exactly the kind of gap that is noticed
    // the day something is discarded that should have been held.
    const orphaned = forTarget(properties, "subscription").filter((p) => !p.on.includes("topic"));
    if (subscribers.length === 0 && orphaned.length > 0) {
      losses.push({
        construct: "dlq",
        at: name,
        fidelity: "none",
        detail:
          `A topic's dead-lettering and sessions belong to its subscriptions, and nothing in the ` +
          `model subscribes to this one — so ${orphaned.map((p) => `\`${p.key}\``).join(", ")} is ` +
          `declared nowhere. Whatever subscribes later has to set it, or the model is wrong about ` +
          `this pipe.`,
      });
    }

    for (const subscriber of subscribers) {
      const built = subscriptionResource(pipe, subscriber, resource, options, properties);
      lines.push(...built.lines);
      losses.push(...built.losses);
      problems.push(...built.problems);
    }
  }

  return { lines, losses, problems, needsPremium: mapped.needsPremium };
}

/** One subscription, with the filter the model implies. */
function subscriptionResource(
  pipe: PipeIr,
  subscriber: Subscriber,
  parent: string,
  options: Options,
  inherited: readonly Property[],
): Built {
  const losses: Loss[] = [];
  const problems: NameProblem[] = [];
  const at = `${qnameOf(pipe)}/${subscriber.name}`;

  const nameProblem = checkName(subscriber.name, "subscription", at);
  if (nameProblem !== undefined) problems.push(nameProblem);

  const resource = symbol(`sub_${qnameOf(pipe)}_${subscriber.name}`);

  // Everything the pipe declared that lands on a subscription rather than on the topic: the
  // sessions, the dead-lettering, the time to live.
  const properties: Property[] = [...forTarget(inherited, "subscription")];

  const count = deliveryCount(subscriber.reacts);
  if (count !== undefined) properties.push({ ...count, on: ["subscription"] });

  const lines: string[] = [
    ...comment(
      `\`${subscriber.name}\` of \`${qnameOf(subscriber.service)}\`, subscribed to \`${qnameOf(pipe)}\`.`,
    ),
    `resource ${resource} 'Microsoft.ServiceBus/namespaces/topics/subscriptions@${options.apiVersion}' = {`,
    ...indent([`parent: ${parent}`, `name: '${subscriber.name}'`, ...propertyBlock(properties)]),
    "}",
    "",
  ];

  // The filter: the types this subscription reacts to, and whatever its `where` says.
  const clauses: { sql: string; why: string }[] = [];

  if (options.typeFilters && subscriber.types.length > 0) {
    const carried = (pipe.carries ?? []).length;
    // Where the topic carries only what this subscription wants, a type filter adds nothing.
    if (carried === 0 || carried > subscriber.types.length) {
      clauses.push({
        sql: typeFilter(subscriber.types),
        why:
          `the message types this subscription reacts to. The sender sets \`${LABEL}\` to the ` +
          `message's qualified 7K name, which is the convention this filter depends on`,
      });
    }
  }

  for (const react of subscriber.reacts) {
    if (react.where === undefined) continue;
    const filter = whereFilter(react.where);
    if (filter.sql === undefined) {
      losses.push({
        construct: "where",
        at,
        fidelity: "none",
        detail:
          `The \`where\` on this subscription is not expressed as a filter because ${filter.why ?? "it is unsupported"}. ` +
          `Without it the subscription receives more than the model says it wants, and the handler has ` +
          `to decline the rest — which 7K reports as a \`filtered\` outcome the broker never produced.`,
      });
      continue;
    }
    clauses.push({ sql: filter.sql, why: "the subscription's `where`, which reads the envelope (D56)" });
  }

  if (clauses.length > 0) {
    const ruleName = "sevenk";
    const ruleProblem = checkName(ruleName, "rule", at);
    if (ruleProblem !== undefined) problems.push(ruleProblem);

    lines.push(
      ...clauses.flatMap((c) => comment(c.why)),
      `resource ${symbol(`${resource}_rule`)} 'Microsoft.ServiceBus/namespaces/topics/subscriptions/rules@${options.apiVersion}' = {`,
      ...indent([
        `parent: ${resource}`,
        `name: '${ruleName}'`,
        "properties: {",
        ...indent([
          "filterType: 'SqlFilter'",
          "sqlFilter: {",
          ...indent([`sqlExpression: '${clauses.map((c) => `(${c.sql})`).join(" AND ").replace(/'/g, "\\'")}'`]),
          "}",
        ]),
        "}",
      ]),
      "}",
      "",
    );
  }

  return { lines, losses, problems, needsPremium: false };
}

/** The parameters and the namespace the resources hang from. */
function preamble(options: Options, createNamespace: boolean, needsPremium: boolean): string[] {
  const premium = needsPremium || options.sku === "premium";
  const parentRef = symbol("namespace");

  const lines: string[] = [
    ...comment(
      "What the model does not say. Everything below this is a literal, so that a change to the " +
        "model shows up as a change to the template.",
    ),
    `@description('The Service Bus namespace these entities belong to.')`,
    `param ${options.namespaceParam} string`,
    "",
  ];

  if (createNamespace) {
    lines.push(
      `@description('Where the namespace lives.')`,
      "param location string = resourceGroup().location",
      "",
      ...comment(
        `\`sku\` was \`${options.sku}\` at generation time, and the entities below were written for it` +
          (premium ? " — a premium namespace is what lets a per-message cap be set" : ""),
      ),
      `resource ${parentRef} 'Microsoft.ServiceBus/namespaces@${options.apiVersion}' = {`,
      ...indent([
        `name: ${options.namespaceParam}`,
        "location: location",
        "sku: {",
        ...indent([`name: '${premium ? "Premium" : "Standard"}'`, `tier: '${premium ? "Premium" : "Standard"}'`]),
        "}",
      ]),
      "}",
      "",
    );
  } else {
    lines.push(
      ...comment(
        "The namespace is older than the model and shared with things it does not know about, so it " +
          "is referenced rather than declared. `createNamespace` changes that.",
      ),
      `resource ${parentRef} 'Microsoft.ServiceBus/namespaces@${options.apiVersion}' existing = {`,
      ...indent([`name: ${options.namespaceParam}`]),
      "}",
      "",
    );
  }

  return lines;
}

export const bicep: Provider = {
  name: "bicep",
  target: "Azure Service Bus (Bicep)",
  layouts: ["per-declaration", "per-package", "single"],
  options: OPTIONS,

  generate(request: Request): Generated {
    const options: Options = {
      apiVersion: String(request.options["apiVersion"] ?? "2022-10-01-preview"),
      sku: request.options["sku"] === "premium" ? "premium" : "standard",
      namespaceParam: String(request.options["namespaceParam"] ?? "serviceBusNamespace"),
      subscriptions: request.options["subscriptions"] !== false,
      typeFilters: request.options["typeFilters"] !== false,
    };
    const createNamespace = request.options["createNamespace"] === true;

    const built: { decl: Decl; built: Built }[] = [];
    const refusals: Refusal[] = [];

    for (const decl of request.selected) {
      if (decl.kind !== "pipe") continue;

      const perDecl = request.optionsFor(decl);
      const result = pipeResources(decl, request.model, {
        ...options,
        subscriptions: perDecl["subscriptions"] !== false,
        typeFilters: perDecl["typeFilters"] !== false,
      });

      if (result.problems.length > 0) {
        for (const problem of result.problems) {
          refusals.push({
            at: qnameOf(decl),
            declared: problem.declared,
            because: problem.because,
            draft: [
              {
                path: pathFor(decl, request.layout),
                content: `${[
                  ...HEADER,
                  "",
                  ...comment(`7K: ${problem.at} declares ${problem.declared}. ${problem.because}`),
                  // A deliberate failure, so a forgiving run cannot be mistaken for a finished one.
                  `#disable-next-line no-unused-params`,
                  `param sevenkRefused string = fail('7K: ${problem.at} cannot be deployed by this provider.')`,
                ].join("\n")}\n`,
                losses: [],
                from: [qnameOf(decl)],
              },
            ],
          });
        }
        continue;
      }

      if (result.lines.length > 0 || result.losses.length > 0) built.push({ decl, built: result });
    }

    const artifacts = group(built, request.layout, options, createNamespace);
    const deploy = request.options["deployFiles"] !== false ? aside(artifacts, options) : [];

    return { artifacts: [...artifacts, ...deploy], refusals };
  },
};

/**
 * The files beside the templates: a parameter file each, one preview, one README.
 *
 * `from` is empty on all of them, because no declaration produced them — they are what it takes to
 * point the templates somewhere, which is a fact about a deployment and not about the model.
 */
function aside(templates: readonly Artifact[], options: Options): Artifact[] {
  if (templates.length === 0) return [];
  const paths = templates.map((t) => t.path);
  const files = [
    ...paths.map((path) => parameters(path, options.namespaceParam)),
    whatIf(),
    readme(paths, options.namespaceParam, options.sku),
  ];
  return files.map((file) => ({ path: file.path, content: file.content, losses: [], from: [] }));
}

const pathFor = (decl: Decl, layout: Request["layout"]): string => {
  if (layout === "single") return "main.bicep";
  if (layout === "per-package") return `${decl.id.pkg === "" ? "root" : decl.id.pkg}.bicep`;
  return `${decl.id.pkg === "" ? "root" : decl.id.pkg}/${decl.id.name}.bicep`;
};

function group(
  built: readonly { decl: Decl; built: Built }[],
  layout: Request["layout"],
  options: Options,
  createNamespace: boolean,
): Artifact[] {
  const template = (entries: readonly { decl: Decl; built: Built }[]): string => {
    const needsPremium = entries.some((e) => e.built.needsPremium);
    const body = entries.flatMap((e) => [...e.built.lines]);
    // Nothing to declare: a pipe whose every resource was lost still needs no file.
    if (body.length === 0) return "";
    return `${[
      ...HEADER,
      "",
      "targetScope = 'resourceGroup'",
      "",
      ...preamble(options, createNamespace, needsPremium),
      ...body,
    ]
      .join("\n")
      .trimEnd()}\n`;
  };

  const made = (
    path: string,
    entries: readonly { decl: Decl; built: Built }[],
  ): Artifact | undefined => {
    const content = template(entries);
    return content === ""
      ? undefined
      : {
          path,
          content,
          losses: entries.flatMap((e) => e.built.losses),
          from: entries.map((e) => qualified(e.decl.id)),
        };
  };

  if (layout === "per-declaration") {
    return built
      .map((entry) => made(pathFor(entry.decl, layout), [entry]))
      .filter((a): a is Artifact => a !== undefined);
  }

  if (layout === "per-package") {
    const byPackage = new Map<string, { decl: Decl; built: Built }[]>();
    for (const entry of built) {
      const key = entry.decl.id.pkg;
      byPackage.set(key, [...(byPackage.get(key) ?? []), entry]);
    }
    return [...byPackage]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([, entries]) => made(pathFor(entries[0]!.decl, layout), entries))
      .filter((a): a is Artifact => a !== undefined);
  }

  const one = made("main.bicep", built);
  return one === undefined ? [] : [one];
}

export default bicep;
